wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.9
    start_time: 1701344724.670912
    t:
      1:
      - 1
      - 41
      - 48
      - 51
      - 54
      - 55
      - 79
      2:
      - 1
      - 41
      - 48
      - 51
      - 54
      - 55
      - 79
      3:
      - 17
      - 23
      - 37
      4: 3.8.9
      5: 0.13.2
      8:
      - 5
batch_size:
  desc: null
  value: 12
bone_test:
  desc: null
  value: SP02-01
bone_train:
  desc: null
  value:
  - SP02-02
  - SP02-03
  - SP02-04
  - SP02-05
epochs:
  desc: null
  value: 1
learning_rate:
  desc: null
  value: 0.0001
loss_coefficients (adv, pix):
  desc: null
  value:
  - 0.001
  - 1.0
warmup_batches:
  desc: null
  value: 0
