wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.9
    start_time: 1701767621.612163
    t:
      1:
      - 1
      - 41
      - 48
      - 51
      - 54
      - 55
      - 79
      2:
      - 1
      - 41
      - 48
      - 51
      - 54
      - 55
      - 79
      3:
      - 17
      - 23
      - 37
      4: 3.8.9
      5: 0.13.2
      8:
      - 5
batch_size:
  desc: null
  value: 12
epochs:
  desc: null
  value: 5
femur_test:
  desc: null
  value: '001'
femur_train:
  desc: null
  value:
  - '002'
  - '013'
  - '015'
learning_rate:
  desc: null
  value: 0.0001
loss_coefficients (adv, pix, cont):
  desc: null
  value:
  - 0.001
  - 1.0
  - 0.06
warmup_batches:
  desc: null
  value: 0
