wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.9
    start_time: 1665570932.03896
    t:
      1:
      - 1
      - 41
      - 48
      - 54
      - 55
      2:
      - 1
      - 41
      - 48
      - 54
      - 55
      3:
      - 17
      - 23
      - 37
      4: 3.8.9
      5: 0.13.2
      8:
      - 5
batch_size:
  desc: null
  value: 4
epochs:
  desc: null
  value: 5
femur_test:
  desc: null
  value: '01'
femur_train:
  desc: null
  value:
  - '15'
  - '21'
  - '74'
input_type:
  desc: null
  value: clinical/low-res/linear
learning_rate:
  desc: null
  value: 0.0002
loss_coefficients (adv, pix):
  desc: null
  value:
  - 0.005
  - 0.01
output_type:
  desc: null
  value: micro
