wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.9
    start_time: 1698945448.772505
    t:
      1:
      - 1
      - 41
      - 48
      - 51
      - 54
      - 55
      2:
      - 1
      - 41
      - 48
      - 51
      - 54
      - 55
      3:
      - 17
      - 23
      4: 3.8.9
      5: 0.13.2
      8:
      - 5
